### ISSUE TITLE
Kubernetes deployment yields errors in the UI.

### ISSUE THREAD

**Issue by twitchax** [rancher/old-vm#117]
Deploying to kubernetes yields javascript errors in the UI.

```
uncaught at t TypeError: Cannot read property 'length' of null
    at o (http://ranchervm.k8s.ajroney.com/0.dashboard.js:10:26555)
    at r.render (http://ranchervm.k8s.ajroney.com/index.js:32:19614)
    at c._renderValidatedComponentWithoutOwnerOrContext (http://ranchervm.k8s.ajroney.com/index.js:32:26093)
    at c._renderValidatedComponent (http://ranchervm.k8s.ajroney.com/index.js:32:26305)
    at c._updateRenderedComponent (http://ranchervm.k8s.ajroney.com/index.js:32:25520)
    at c._performComponentUpdate (http://ranchervm.k8s.ajroney.com/index.js:32:25321)
    at c.updateComponent (http://ranchervm.k8s.ajroney.com/index.js:32:24599)
    at c.receiveComponent (http://ranchervm.k8s.ajroney.com/index.js:32:23710)
    at Object.receiveComponent (http://ranchervm.k8s.ajroney.com/index.js:5:30860)
    at c._updateRenderedComponent (http://ranchervm.k8s.ajroney.com/index.js:32:25564)
```

Any idea what might be going on?

**Comment by Oats87** [comment]
There seems to be an issue where if you have no VM's created the initial dashboard will load. After creating a VM the dashboard starts working.

**Comment by twitchax** [comment]
Hmmm, I tried creating a VM via a `kubectl apply`, but that does not address anything.

**Comment by twitchax** [comment]
Hey @LLParse, awesome to see the traction here.  Do you have a current roadmap for the milestone you referenced?

If there are still issues, feel free to loop me in, as well, and I might be able to carve out some time to contribute.

**Comment by LLParse** [comment]
Hello @twitchax ! We will probably require another few weeks to complete the Longhorn integration. 

Seeing as there's interest (and this is a particularly annoying bug), I'll target a bugfix release for early next week and move this out of the milestone. In the meantime, if you want to temporarily adjust your chart, you can use `rancher/vm-frontend:80d4c31` image.

**Comment by twitchax** [comment]
Very cool: I will give that a go and offer any feedback. :)

**Comment by twitchax** [comment]
That images fixes the UI.  Looks like I am not running into an issue similar to #114.

I will add my logs to that thread.

**Comment by LLParse** [comment]
@twitchax Thanks for the feedback.

**Comment by aleksey005** [comment]
He mistakenly created a vm (Windows:7 for not exist rancher/windows:7 docker hub) through Yaml, now the machines created earlier disappeared in the panel, but they work. How to fix the problem?
![image](https://user-images.githubusercontent.com/6145279/50536964-6414c600-0b6b-11e9-8b58-1e6dde7a9f29.png)
![image](https://user-images.githubusercontent.com/6145279/50536968-71ca4b80-0b6b-11e9-8cbe-dc32b7807b5d.png)
**Maybe there is an opportunity to delete a task through kubectl so that this incorrectly created machine is not deployed?**

**Comment by aleksey005** [comment]
I answer my own question:
kubectl delete virtualmachines.vm.rancher.io [virtual machine name]
And all good
![image](https://user-images.githubusercontent.com/6145279/50537252-63c9fa00-0b6e-11e9-99d1-364455d98018.png)
